### PR TITLE
ES2016 and refactor

### PR DESCRIPTION
**Pull request by novemberborn**
First commit upgrades the source to ES2016. I've left tests alone for now but will do that as a follow-up.

Second commit refactors the implementation:

* Change name, when providing linter
* Resolve only ignoreGlobs from the package.json options
* Rename linter key in options to linterName
* Simply pass linter object to lint(), so it doesn't need to return a
function
* Make getting a linter synchronous
* Implement naive error serialization (assumes errors have a message)
* In the main process, change the linter's lintText() to return a
promise
* Reject the aforementioned promise with a proper error if the worker
responds with a serialized error object
* Simplify worker implementation and response object
* Attempt to simplify range conversion

### CODE REVIEW

**Review by gustavnikolaj — APPROVED** [review]
L(Very)GTM :+1:

**Comment by novemberborn** [comment]
Thanks! I've now also converted the tests and found some more stuff to clean up and refactor.

**Comment by gustavnikolaj** [comment]
I'm on my phone, so a plain comment will have to do. :-)

It looks great and I don't have anything to add. There's a few lines in the tests that get a little long for my taste, but that's too nitpicky to be important :-)

**Comment by novemberborn** [comment]
> There's a few lines in the tests that get a little long for my taste, but that's too nitpicky to be important :-)

Yea I noticed that. I used [`lebab`](https://www.npmjs.com/package/lebab) to convert the code and it's a bit eager with its arrow functions. I didn't really want to go through the diff though and readjust… 😄

**Pull request merged**
